name: Tests
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - name: set_var
        if: ${{ github.event_name == 'pull_request' }}
        run: echo FOUNDRY_FUZZ_RUNS=50000 >> $GITHUB_ENV
      - name: use_var
        run: echo foundry fuzz has $FOUNDRY_FUZZ_RUNS runs
      - name: make install
        run: make install
      - name: lint
        run: make lint
      - name: test
        if: ${{ github.event_name == 'pull_request' }}
        run: make test
      - name: test deep
        if: ${{ github.event_name == 'push' }}
        run: make test_deep
