name: Tests
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - uses: cachix/cachix-action@v10
        with:
          name: radicle-drips-hub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: install
        run: make install

      - name: lint
        run: make lint 

      - name: test
        if: ${{ github.event_name == 'pull_request' }}
        run: make test
