name: Tests
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: make install
        run: make install
      - name: lint
        run: make lint
      - name: test
        if: ${{ github.event_name == 'pull_request' }}
        run: make test
      - name: test deep
        if: ${{ github.event_name == 'push' }}
        run: make test_deep
