name: Tests
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: check formatting
        run: forge fmt --check
      - name: make fuzz tests on master branch extensive
        if: ${{ github.event_name == 'push' }}
        run: echo FOUNDRY_FUZZ_RUNS=50000 >> $GITHUB_ENV
      - name: run tests
        run: forge test --deny-warnings --build-info
      - name: run Slither
        uses: crytic/slither-action@v0.2.0
        with:
          slither-version: '0.9.2'
          # A workaround for https://github.com/crytic/slither-action/issues/49,
          # requires passing `--build-info` to `forge test`
          ignore-compile: true
