name: Tests
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - uses: CodeSandwich/foundry-toolchain
        with:
          version: nightly-6547691c6123c1bdbed770fcd245f1e63092befe

      - name: install
        run: make install

      - name: lint
        run: make lint 

      - name: test
        if: ${{ github.event_name == 'pull_request' }}
        run: make test

      - name: test deep
        if: ${{ github.event_name == 'push' }}
        env:
          FOUNDRY_FUZZ_RUNS: 50000
        run: make test
